baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My testing site'
theme = 'hello-friend-ng'
paginate     = 10

[params]
 homeSubtitle = "A simple and beautiful blog"


  enableThemeToggle = true

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = true

  # Metadata mostly used in document's head
  description = "My new homepage or blog"
  keywords = "homepage, blog"
  images = [""]

  [params.author]
    name = "Jean Karl Maxwell"

  [params.footer]
    rss = true
    author = true

    topText = ["topText"]

  [[params.social]]
  name = "github"
  url = "https://github.com/JCMaxwell12"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
